//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chat User:  ähnelt.
        /// </summary>
        internal static string ChatUser {
            get {
                return ResourceManager.GetString("ChatUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connected ähnelt.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display Messages saved in
        /// ähnelt.
        /// </summary>
        internal static string DisplayMessages {
            get {
                return ResourceManager.GetString("DisplayMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;Enter Room Number&gt; ähnelt.
        /// </summary>
        internal static string EnterRoomNumber {
            get {
                return ResourceManager.GetString("EnterRoomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following error is trapped by the chat server ähnelt.
        /// </summary>
        internal static string ErrorFromServer {
            get {
                return ResourceManager.GetString("ErrorFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  for  ähnelt.
        /// </summary>
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image Files(*.BMP;*.JPG;*.GIF)|*.BMP;*.JPG;*.GIF|All files (*.*)|*.* ähnelt.
        /// </summary>
        internal static string ImageFilesFilter {
            get {
                return ResourceManager.GetString("ImageFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Picture ähnelt.
        /// </summary>
        internal static string InvalidPicture {
            get {
                return ResourceManager.GetString("InvalidPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ISS Chat ähnelt.
        /// </summary>
        internal static string ISS_Chat {
            get {
                return ResourceManager.GetString("ISS_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;Key in Message&gt; ähnelt.
        /// </summary>
        internal static string KeyInMessage {
            get {
                return ResourceManager.GetString("KeyInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Media Files(*.WAV;*.MPG;*.WMV;*.WMA;*.BMP;*.JPG;*.GIF)|*.BMP;*.JPG;*.GIF;*.WAV;*.MPG;*.WMV;*.WMA) ähnelt.
        /// </summary>
        internal static string MediaFilesFilter {
            get {
                return ResourceManager.GetString("MediaFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        /// ähnelt.
        /// </summary>
        internal static string NewLine {
            get {
                return ResourceManager.GetString("NewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error:Possibily Network Error or Server has shut down ähnelt.
        /// </summary>
        internal static string PossibilyNetworkError {
            get {
                return ResourceManager.GetString("PossibilyNetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read&gt; ähnelt.
        /// </summary>
        internal static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die room assigned=  ähnelt.
        /// </summary>
        internal static string RoomAssigned {
            get {
                return ResourceManager.GetString("RoomAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server/Connection Error
        ///Do you want to Save Display Messages? ähnelt.
        /// </summary>
        internal static string ServerConnectionError {
            get {
                return ResourceManager.GetString("ServerConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ************************************************* ähnelt.
        /// </summary>
        internal static string Stars {
            get {
                return ResourceManager.GetString("Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die that support rtf format ähnelt.
        /// </summary>
        internal static string ThatSupportRtfFormat {
            get {
                return ResourceManager.GetString("ThatSupportRtfFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Usage: ChatClient &lt;host&gt; &lt;port&gt; ähnelt.
        /// </summary>
        internal static string UsageChatClient {
            get {
                return ResourceManager.GetString("UsageChatClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Usage: ChatServer &lt;port&gt; &lt;num_room&gt; ähnelt.
        /// </summary>
        internal static string UsageChatServer {
            get {
                return ResourceManager.GetString("UsageChatServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can view it using WinWord or any Editor/Reader
        /// ähnelt.
        /// </summary>
        internal static string ViewItUsingWinWord {
            get {
                return ResourceManager.GetString("ViewItUsingWinWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waiting for Connection... ähnelt.
        /// </summary>
        internal static string WaitingForConnection {
            get {
                return ResourceManager.GetString("WaitingForConnection", resourceCulture);
            }
        }
    }
}
